In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [4]:
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
A = np.arange(24).reshape((3,4,2))

In [11]:
A.flatten(order="C")
A.flatten(order="F")

array([ 0,  8, 16,  2, 10, 18,  4, 12, 20,  6, 14, 22,  1,  9, 17,  3, 11,
       19,  5, 13, 21,  7, 15, 23])

In [12]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
A.ravel(order="F")

array([ 0,  8, 16,  2, 10, 18,  4, 12, 20,  6, 14, 22,  1,  9, 17,  3, 11,
       19,  5, 13, 21,  7, 15, 23])

In [15]:
A.ravel(oreder="K")

TypeError: 'oreder' is an invalid keyword argument for ravel()

In [17]:
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])
c = np.concatenate((x,y,z))
c

array([11, 22, 18,  7,  6,  1,  3,  5])

In [19]:
x = np.array(range(12))
x = x.reshape((2,3,2))
y = np.array(range(100,112))
y = y.reshape((2,3,2))
z = np.concatenate((x,y), 1)
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]
  [100 101]
  [102 103]
  [104 105]]

 [[  6   7]
  [  8   9]
  [ 10  11]
  [106 107]
  [108 109]
  [110 111]]]


In [23]:
a = np.dstack((x,y)) # np concatenate((x,y), 2)
b = np.vstack((x,y)) # np concatenate((x,y), 0)
c = np.hstack((x,y)) # np concatenate((x,y), 1)

In [26]:
np.dsplit(a,2)
np.hsplit(a,1)

[array([[[  0,   1, 100, 101],
         [  2,   3, 102, 103],
         [  4,   5, 104, 105]],
 
        [[  6,   7, 106, 107],
         [  8,   9, 108, 109],
         [ 10,  11, 110, 111]]])]

In [27]:
x = np.array([2, 5, 18, 14, 4])
y = x[:, np.newaxis]
print(y)

#1차원 배열은 벡터, 2차원부터는 행렬, 대괄호가 하나면 1차원(벡터), 대괄호가 2개면 2차원(매트릭스) ㅌ = 

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


In [28]:
x = np.array([[1, 2], [3,4]])
np.tile(x, (3,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [31]:
#concatenate는 더하기 기호, 일반적으로 차원을 유지한다. 차원 갯수가 많으면 축을 어떻게 하느냐에 따라 달라지지만 거의 차원을 유지한다. tile은 곱하기 기호 
a = [1,2,3]
b = np.tile(a,(2,1))
b

array([[1, 2, 3],
       [1, 2, 3]])

In [32]:
A = np.array([3,4,5])
B = np.array([1,9,0])
print(np.row_stack((A,B)))
print(np.column_stack((A,B)))
print(np.shape(A))

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]
(3,)


In [33]:
#stack 계열 함수들은 차원이 하나씩 늘어난다. 근데 매트릭스 데이터는 차원을 유지한다. 

In [35]:
A = np.array([[3,4,5],[1,9,0],[4,6,8]])
print(A.shape)
print(np.column_stack((A, A)).shape)
print(np.row_stack((A, A)).shape)

(3, 3)
(3, 6)
(6, 3)


In [36]:
print(np.concatenate((A, A)).shape)
print(np.concatenate((A, A),1).shape)


(6, 3)
(3, 6)


In [37]:
A = np.array([4,7,3,4,2,8])
C = (A==4)
print(C, type(C))
LT = (A < 5)
print(LT, type(LT))


[ True False False  True False False] <class 'numpy.ndarray'>
[ True False  True  True  True False] <class 'numpy.ndarray'>


In [38]:
B = np.random.normal(0, 3, (3, 3))
#0보다 큰 숫자의 위치를 확인해보세요
nz = (B > 0)
print(nz.astype(np.int))
nz.nonzero()
#0이 아닌 숫자를 출력해보세요
print(B[nz.nonzero()])
#0이 아닌 숫자를 1차원으로 펼쳐서 위치를 출력해보세요
print(np.flatnonzero(nz))
#0이 아닌 숫자의 개수를 출력해보세요
np.count_nonzero(nz)

[[0 1 1]
 [0 1 0]
 [0 1 0]]
[1.89776417 1.50800893 0.16116373 0.10239528]
[1 2 4 7]


4

In [42]:
a = np.array([1,2,3,4]).reshape((2,2))
b = np.array([1,1,1,1]).reshape((2,2))

print(a @ b)
print(np.dot(a,b))
print(a * b)
print(np.cross(a,b))

a * b

[[3 3]
 [7 7]]
[[3 3]
 [7 7]]
[[1 2]
 [3 4]]
[-1 -1]


array([[1, 2],
       [3, 4]])

In [41]:
a = np.matrix([1,2,3,4]).reshape((2,2))
b = np.matrix([1,1,1,1]).reshape((2,2))
a * b

matrix([[3, 3],
        [7, 7]])

In [43]:
#행렬의 곱셉이 내적과 외적이 있다. 
#내적 곱은 dot곱이고 외적곱은 교차곱이다. 


In [44]:
import numpy as np
x = np.array([1,5,2])
y = np.array([7,4,1])
print(x+y)
print(x*y)
print(x-y)
print(x/y)
print(x%y)

[8 9 3]
[ 7 20  2]
[-6  1  1]
[0.14285714 1.25       2.        ]
[1 1 0]


In [70]:
a = np.array([1,2,3,4]).reshape((2,2))
b = np.array([1,1,1,1]).reshape((2,2))

c = a.reshape(1,4)
d = b.reshape(4,1)
e =  c @ d
e.flatten()

np.dot(a.ravel(),b.ravel())

#flatten과 ravel은 기능은 같다. matrix을 1차 ndarray로 풀어주는 함수

10

In [71]:
import numpy as np

xm = np.matrix( ((2,3), (3, 5)) )
xa = np.array( ((2,3), (3, 5)) )
print(np.mat(xa) * xm)
print(np.asmatrix(xa) * xm)

[[13 21]
 [21 34]]
[[13 21]
 [21 34]]


In [74]:
a = [0,0,1]
b = [0,1,0]

xm = np.array(a)
bn = np.array(b)

np.cross(xm,bn)


array([-1,  0,  0])

In [75]:
out = np.random.randint(1, 7, size=10)
out

array([2, 5, 2, 1, 4, 5, 5, 1, 2, 4])

In [76]:
out = np.random.randint(2, size=10)
out

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [77]:
out = np.random.randint(1, size=10)
out

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
print(np.random.randint(5, size=(2,4)))

[[2 3 0 3]
 [4 4 2 0]]


In [79]:
from numpy.random import choice
choice(5,3)

array([4, 0, 0])

In [80]:
choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 3])

In [84]:
aa_mille_arr = ['pooh','rabbit','piglet','Christoper']
print(np.random.choice(aa_mille_arr, 5, p=[0.5, 0.1, 0.1, 0.3]))

['piglet' 'pooh' 'rabbit' 'pooh' 'pooh']


In [88]:
choice(5, 3, replace=False)

array([4, 0, 2])

In [97]:
from numpy.random import permutation
permutation(np.arange(5))[:3]

array([4, 1, 3])

In [103]:
from numpy.random import random_sample
(5.9+3.4) * (random_sample((3,4))) - 4.67

array([[ 1.99961225, -3.33214807, -3.13547203,  0.95394341],
       [-1.87317717, -2.93549834, -3.03158455,  1.22713173],
       [-2.46409751,  2.79319897, -2.36882455,  1.03295885]])

# 

In [104]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [105]:
np.sum(b)

66

In [106]:
np.sum(b,axis=0)
#각 행별로 각 열별로 연산이 가능하다. axis를 주게 되면

array([12, 15, 18, 21])

In [107]:
np.sum(b,axis=1)

array([ 6, 22, 38])