In [5]:
import numpy as np
from numpy.lib.stride_tricks import as_strided
n = 5; k=2
a = np.linspace(1, n, n); aid = id(a)
as_strided(a,(k,n),(8,8))
as_strided(a,(k,n-k+1), (8,8))
# 간격이 균등한 것이 linspace
# k는 이동평균의 상수값이다.

def shift1(x,k):
    return np.vstack(x[i:n-k+i+1] for i in range(k))
def shift2(x,k):
    return as_strided(x, (k, n-k+1), (x.itemsize,)*2)
b = shift1(a, k); b, id(b) == aid
c = shift2(a, k); c, id(c) == aid

a.itemsize


C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  # Remove the CWD from sys.path while we load stuff.


8

In [11]:
n, k = 100, 10
t = np.linspace(0., 1., n)
x = t + 0.1 * np.random.randn(n)
#평균이 0인 정규분포를 만든다.
y = shift2(x,k)
print(y.shape)
x_avg = y.mean(axis=0)
x_avg

#91개의 데이터가 나오는데 첫 9개는 이동평균이 안나오기 때문이다.
# % 붙은 키워드는 매직키워드라고 주피터에서만 쓸 수 있다.

%timeit shift1(x,k)

(10, 91)


C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  # Remove the CWD from sys.path while we load stuff.


24.2 µs ± 1.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
%timeit shift2(x,k)

8.3 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%%timeit 
y = shift1(x,k)

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  # Remove the CWD from sys.path while we load stuff.


26.7 µs ± 2.47 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%%timeit 
y = shift2(x,k)

8.68 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
print(a)
for i in range(k):
    print(n, k, i)

[1. 2. 3. 4. 5.]
100 10 0
100 10 1
100 10 2
100 10 3
100 10 4
100 10 5
100 10 6
100 10 7
100 10 8
100 10 9


In [25]:
x = np.array([5.3, 4.4, 5.4, 5.8, 5.6, 4.8, 5.6, 
              5.6, 5.4, 6.5, 5.1, 5.8, 5,  6.2, 
              5.6, 6.7, 5.2, 5.5, 5.8, 5.1, 5.8, 
              6.7, 5.2, 6, 5.8])
w = 3 #window size
n = x.strides[0]
print(n)
print(x.size)
#x의 사이즈를 물어보는 것이다. 25개가 나올 것이다. 숫자가 25개 있으니까
s = as_strided(x, shape=(x.size-w+1,w), strides=(n,n))
#x라는 배열을 23행 3열로 만든 뒤에 실수이기 때문에 8바이트짜리로 만든다. 행으로 이동해도 8바이트, 열로 이동해도 8바이트
print(s)
np.mean(s,1)
#stride는 몇 바이트짜리인지 물어보는 것이다.

8
25
[[5.3 4.4 5.4]
 [4.4 5.4 5.8]
 [5.4 5.8 5.6]
 [5.8 5.6 4.8]
 [5.6 4.8 5.6]
 [4.8 5.6 5.6]
 [5.6 5.6 5.4]
 [5.6 5.4 6.5]
 [5.4 6.5 5.1]
 [6.5 5.1 5.8]
 [5.1 5.8 5. ]
 [5.8 5.  6.2]
 [5.  6.2 5.6]
 [6.2 5.6 6.7]
 [5.6 6.7 5.2]
 [6.7 5.2 5.5]
 [5.2 5.5 5.8]
 [5.5 5.8 5.1]
 [5.8 5.1 5.8]
 [5.1 5.8 6.7]
 [5.8 6.7 5.2]
 [6.7 5.2 6. ]
 [5.2 6.  5.8]]


array([5.03333333, 5.2       , 5.6       , 5.4       , 5.33333333,
       5.33333333, 5.53333333, 5.83333333, 5.66666667, 5.8       ,
       5.3       , 5.66666667, 5.6       , 6.16666667, 5.83333333,
       5.8       , 5.5       , 5.46666667, 5.56666667, 5.86666667,
       5.9       , 5.96666667, 5.66666667])