In [1]:
from pandas import Series, DataFrame
import pandas as pd

In [2]:
obj = Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4, 7, -5, 3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

#obj는 rangeindex라고 나올 수 있었던 것은 index가 숫자이기 때문이고 obj2의 경우에는 문자이기 때문에 
#index가 그대로 출력 dtype의 경우는 더 큰 쪽으로 가는데 문자와 숫자가 섞여있으면 문자 기준으로 dtype이 가게 된다.

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2[['d','c','a']]
#2개 이상의 위치에 접근하고자 할 때 안에 대괄호를 하나 더 써주어야한다. 

d    4
c    3
a   -5
dtype: int64

In [12]:
obj2[ obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [17]:
Sdata = {'Daegu':2500, 'Busan':71000, 'Seoul':16000, 'Daejeon':5000}
obj3=Series(Sdata)

In [18]:
obj3

Daegu       2500
Busan      71000
Seoul      16000
Daejeon     5000
dtype: int64

In [19]:
city = ['Incheon','Daegu','Seoul','Busan']
obj4 = Series(Sdata, index=city)

In [20]:
obj4

Incheon        NaN
Daegu       2500.0
Seoul      16000.0
Busan      71000.0
dtype: float64

In [21]:
#있는 키만 알아서 데이터를 가져올 수 있다. 

In [22]:
pd.isnull(obj4)

Incheon     True
Daegu      False
Seoul      False
Busan      False
dtype: bool

In [23]:
obj4.notnull()

Incheon    False
Daegu       True
Seoul       True
Busan       True
dtype: bool

In [24]:
obj4

Incheon        NaN
Daegu       2500.0
Seoul      16000.0
Busan      71000.0
dtype: float64

In [25]:
obj3+obj4
#numpy는 이렇게 하면 에러가 발생하지만 pandas는 알아서 만들어준다. 

Busan      142000.0
Daegu        5000.0
Daejeon         NaN
Incheon         NaN
Seoul       32000.0
dtype: float64

In [26]:
obj.index = ['Choi', 'Park', 'Kim', 'Hwang']

In [27]:
obj

Choi     4
Park     7
Kim     -5
Hwang    3
dtype: int64

In [40]:
a = ['Seoul']*3 + ['Daegu']*2
b = list(range(2010,2013)) + list(range(2011,2013))
c = [1.5, 1.7, 3.6, 2.4, 2.9]
data = {'city':a, 'year':b, 'pop':c}
data
frame = DataFrame(data)
frame2 = DataFrame(data, columns=['year', 'city', 'pop','debt'], index=['one', 'two', 'three', 'four', 'five'])

In [41]:
frame
frame2

year   city  pop debt
one    2010  Seoul  1.5  NaN
two    2011  Seoul  1.7  NaN
three  2012  Seoul  3.6  NaN
four   2011  Daegu  2.4  NaN
five   2012  Daegu  2.9  NaN

In [51]:
frame2 = DataFrame(data, columns=['year', 'city', 'pop','debt'], index=['one', 'two', 'three', 'four', 'five'])
data = {'city':a, 'year':b, 'pop':c, 'debt':range(1,6)}

In [52]:
frame2

year   city  pop  debt
one    2010  Seoul  1.5     1
two    2011  Seoul  1.7     2
three  2012  Seoul  3.6     3
four   2011  Daegu  2.4     4
five   2012  Daegu  2.9     5

In [53]:
frame2['city']

one      Seoul
two      Seoul
three    Seoul
four     Daegu
five     Daegu
Name: city, dtype: object

In [55]:
frame2.year

#DataFrame은 열단위 접근이 기본적인 것이다. 

#변수 속성에 따라 밑에 방식이 사용하기 편한데 밑의 방식은 에러가 발생하기 쉽다. 변수 이름 규칙을 안따랐을 때는
#city의 경우에는 오류가 발생하기 쉽다. 불편하더라도 column 이름으로 접근할 때 key값 접근하듯이 ['city']로 접근하는 것이 좋다. 
# 행에 대해서 접근할 때는 .loc를 붙여야한다.
frame2.loc['one']

year     2010
city    Seoul
pop       1.5
debt        1
Name: one, dtype: object

In [57]:
import numpy as np
frame2['debt'] = np.arange(5)
frame2
#arange는 실수도 처리할 수 있다. 

year   city  pop  debt
one    2010  Seoul  1.5     0
two    2011  Seoul  1.7     1
three  2012  Seoul  3.6     2
four   2011  Daegu  2.4     3
five   2012  Daegu  2.9     4

In [94]:
val = Series([-1.2, -1.5, -1.7], index=['two','four','five'])

frame2['debt'] = val
frame2

#column 전체를 덮어씌면서 one과 three는 다시 누락된다. series가 채워질 때 column 단위로 채워진다. 

year   city  pop  debt
one    2010  Seoul  1.5   NaN
two    2011  Seoul  1.7  -1.2
three  2012  Seoul  3.6   NaN
four   2011  Daegu  2.4  -1.5
five   2012  Daegu  2.9  -1.7

In [64]:

frame2['eastern'] = frame2.city == 'Daegu' #언제든지 추가를 할 수 있다. 
del frame2['eastern']
frame2


frame2


year   city  pop  debt
one    2010  Seoul  1.5   NaN
two    2011  Seoul  1.7  -1.2
three  2012  Seoul  3.6   NaN
four   2011  Daegu  2.4  -1.5
five   2012  Daegu  2.9  -1.7

In [65]:
frame2.loc['six'] = frame2.loc['five']
frame2

year   city  pop  debt
one    2010  Seoul  1.5   NaN
two    2011  Seoul  1.7  -1.2
three  2012  Seoul  3.6   NaN
four   2011  Daegu  2.4  -1.5
five   2012  Daegu  2.9  -1.7
six    2012  Daegu  2.9  -1.7

In [77]:
frame2 = frame2.drop('six')


In [81]:
frame2.columns

Index(['year', 'city', 'pop', 'debt'], dtype='object')

In [82]:
frame2.values

array([[2010, 'Seoul', 1.5, nan],
       [2011, 'Seoul', 1.7, -1.2],
       [2012, 'Seoul', 3.6, nan],
       [2011, 'Daegu', 2.4, -1.5],
       [2012, 'Daegu', 2.9, -1.7]], dtype=object)

In [83]:
frame2

year   city  pop  debt
one    2010  Seoul  1.5   NaN
two    2011  Seoul  1.7  -1.2
three  2012  Seoul  3.6   NaN
four   2011  Daegu  2.4  -1.5
five   2012  Daegu  2.9  -1.7

In [95]:
frame2

year   city  pop  debt
one    2010  Seoul  1.5   NaN
two    2011  Seoul  1.7  -1.2
three  2012  Seoul  3.6   NaN
four   2011  Daegu  2.4  -1.5
five   2012  Daegu  2.9  -1.7

In [91]:
arr = frame2.values

In [96]:
arr[0][-1] = -1.1
arr[2][-1] = -1.4

In [98]:
frame3 = DataFrame(arr, index=frame2.index, columns=frame2.columns)
frame3

year   city  pop debt
one    2010  Seoul  1.5 -1.1
two    2011  Seoul  1.7 -1.2
three  2012  Seoul  3.6 -1.4
four   2011  Daegu  2.4 -1.5
five   2012  Daegu  2.9 -1.7

In [99]:
# Read: pandas의 자료 values를 다른 변수에 저장
# Modify: 따로 저장한 이름을 numpy 로 연산
# Write 연산결과를 다시 pandas의 자료형으로 다시 생성


In [100]:
frame3.values

array([[2010, 'Seoul', 1.5, -1.1],
       [2011, 'Seoul', 1.7, -1.2],
       [2012, 'Seoul', 3.6, -1.4],
       [2011, 'Daegu', 2.4, -1.5],
       [2012, 'Daegu', 2.9, -1.7]], dtype=object)

In [101]:
arr2 = frame3.values

In [102]:
arr2

array([[2010, 'Seoul', 1.5, -1.1],
       [2011, 'Seoul', 1.7, -1.2],
       [2012, 'Seoul', 3.6, -1.4],
       [2011, 'Daegu', 2.4, -1.5],
       [2012, 'Daegu', 2.9, -1.7]], dtype=object)

In [104]:
frame4 = frame3[['year','city']]

In [105]:
frame4
#추출해 내고자 하는 데이터만 대괄호를 입혀서 뽑아내면 된다.

year   city
one    2010  Seoul
two    2011  Seoul
three  2012  Seoul
four   2011  Daegu
five   2012  Daegu

In [109]:
pd.value_counts(frame4['year'])

2011    2
2012    2
2010    1
Name: year, dtype: int64

In [110]:
frame4

year   city
one    2010  Seoul
two    2011  Seoul
three  2012  Seoul
four   2011  Daegu
five   2012  Daegu

In [114]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4],
                  'Qu2': [2, 3, 1, 2, 3],
                  'Qu3': [1, 5, 2, 4, 4]})
result = data.apply(pd.value_counts).fillna(0)
result

#apply를 적용하면 여러 컬롬에 한꺼번에 적용이 가능하다.

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0